language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t weronikasw/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true weronikasw/docker-react npm run test